services:
  - type: web
    name: research_assistant-backend
    env: python
    buildCommand: ./render_build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: EURI_API_KEY
        sync: false

  - type: web
    name: research_assistant-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
